### PR TITLE
Fix for #113: Failed to setup without Internet.

### PR DESCRIPTION
**Pull request by glenn20**
Fix for Issue #113.

Trap error on attempt to connect to BoM services in async_setup_entry() and raise ConfigEntryNotReady so HA will retry the config. HA will keep retrying the config and after network access is available, the config setup completes successfully.

Until the config setup completes, devices will have "unavailable" status.

### CODE REVIEW

**Comment by Makin-Things** [comment]
@glenn20 thanks so much for helping with this. I will do a bunch of testing tomorrow.

**Comment by Makin-Things** [comment]
image
So it seems to work ok, although I got some unexpected results. In this image at 14:01 my internet was not available, yet it claims to have succeeded, but it also didn't fetch any data. The next 2 attempts at 14:11 and 14:21 (internet still unavailable) I got slightly different results. Not sure why.

**Comment by Makin-Things** [comment]
Ok, I think I have tested all the scenarios and it recovers properly. Things I tested where:
- No internet while HA starts;
- Losing internet while running; and
- Trying to set up without internet.
For the last one the error message (see below isn't that descriptive).
image

**Comment by glenn20** [comment]
Thanks Simon. I would expect that this PR would only impact on the first scenario: No internet while HA starts. It won't help with the other scenarios. The other scenarios will need to be addressed separately.

**Comment by Makin-Things** [comment]
So the first 2 scenarios are fine. It does recover if you lose internet while it is already running.
The last one is also ok. You can't set up the integration without internet (it should fail). The error message just doesn't really help, but you should know your internet is broken before then (when you get the list of all the integrations you can choose from all the icons fail to load).

**Pull request merged**
