### PR TITLE
Issue 37: Read warnings data from BoM

### PR DESCRIPTION
**Pull request by glenn20**
This PR addresses requests to support BoM warnings (see Issue #37).

Data is collected from the BoM warnings API.

This data may be made available through an additional `warnings` sensor which can be used in scripts and automations. New or updated lovelace cards would be required to display this data.

The state of the sensor is the number of warnings and the warnings data is stored as a list in the "warnings" attribute of the sensor.

```
sensor.melbourne_forecast_warnings:
- state: 1
- Attributes:
      response_timestamp: 2022-05-16T13:03:47Z
      copyright: This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). 
          You must not use, copy or share this API without express permission from the Bureau. Please contact us for more 
          information. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details.
      attribution: Data provided by the Australian Bureau of Meteorology
      warnings: 
      - id: VIC_MW005_IDV20600
        type: marine_wind_warning
        title: Marine Wind Warning for Victoria
        short_title: Marine Wind Warning
        state: VIC
        warning_group_type: minor
        issue_time: '2022-05-16T12:00:00Z'
        expiry_time: '2022-05-16T19:00:00Z'
        phase: cancelled
      friendly_name: Melbourne Forecast Warnings
```

### CODE REVIEW

**Comment by darek-margas** [comment]
Can someone tell me pls how to add this optional warning sensor?

**Comment by glenn20** [comment]
> Can someone tell me pls how to add this optional warning sensor?

There is an example of a template sensor by StormyKnight17 on the Issues page, which is where most of the useful dicussion happened: https://github.com/bremor/bureau_of_meteorology/issues/37#issuecomment-1129490916.

**Comment by darek-margas** [comment]
> There is an example of a template sensor by StormyKnight17 on the Issues page, which is where most of the useful dicussion happened

Thanks, this seems to be used once I see this sensor but I simply don't have it. I bet I need to enable it but was unable to figure out how. All the rest works since ages ago.

**Comment by glenn20** [comment]
Reaching into my memory here...I believe you need to enable the warning sensor in the integration config.

**Comment by darek-margas** [comment]
> Reaching into my memory here...I believe you need to enable the warning sensor in the integration config.

Sounds good but where is this config?

**Comment by DavidFW1960** [comment]
You can either temove the integration and re add it or you can reconfigure it. Its got a menu on the integrations page for it

**Pull request merged**
