### PR TITLE
Replace pytz with zoneinfo. Fix for #222

### PR DESCRIPTION
**Pull request by dbiczo**
Fix "Detected blocking call to open inside the event loop" warnings by replacing pytz with zoneinfo.

### CODE REVIEW

**Comment by Makin-Things** [comment]
@dbiczo thanks for this PR. For some reason I had not even been getting these warnings (probably because I Only use it for forecast information). I assume you have fully tested that it doesn't break anything else. It looks like a fairly trivial change.

**Comment by dbiczo** [comment]
Yes, tested over a full day. Havn't tested setup flow but don't think it will affect that.

**Comment by Makin-Things** [comment]
Awesome. Thanks I will merge and do a release.

**Comment by Makin-Things** [comment]
I did the release and it broke for me so I have removed it for now. It looks like there is a typo in the fix you submitted.
` File "/config/custom_components/bureau_of_meteorology/weather.py", line 8, in <module>
    import zoneifo
ModuleNotFoundError: No module named 'zoneifo'`

I will edit on main and retry.

Actually I think line 8 should simply be removed since you added the import needed on line 18. Do you agree?

**Comment by dbiczo** [comment]
Thanks. Sorry for the typo. I tested live on my setup and copied the changes to the pull request.

**Comment by dbiczo** [comment]
I was copying what was there for pytz and both lines were there.

**Comment by Makin-Things** [comment]
Yep, they both need to be there. I did a quick test without the first one and got errors. Will do a new release shortly.

**Comment by Makin-Things** [comment]
Release 1.3.2 is done and gives me no errors.

**Comment by dbiczo** [comment]
Great. Thanks for you help.

**Comment by fabienval** [comment]
That commit introduce error #226 since we are no longer using pytz, but pytz.timezone is still referenced for the UV text

**Pull request merged**
