### PR TITLE
Add shared periodical updating to retrieving weather data

### PR DESCRIPTION
**Pull request by evilmarty**
I noticed that the weather data was not being updated so added that ability to keep information as current as possible. Using a shared update coordinator all updates are debounced and uses callbacks to update all components.

### CODE REVIEW

**Comment by bremor** [comment]
Hey Marty, thanks for the PR. I’m trying to understand what you’ve done but it’s a bit beyond me, I’m just a hobby programmer so I really appreciate your input.

Is this something that is normally done for cloud poll integrations? Is it a workaround for some weirdness that I’ve programmed in? I will spend some more time digesting what you’ve done before releasing as a beta.

**Comment by evilmarty** [comment]
@bremor I'm new to developing components for Home Assistant, so I can't say whether what I've done is good practice. In saying that though I've looked at the [National Weather Service component](https://github.com/home-assistant/core/blob/dev/homeassistant/components/nws/__init__.py#L112) and the [AccuWeather component](https://github.com/home-assistant/core/blob/dev/homeassistant/components/accuweather/__init__.py#L45) on how they retrieve updates and created a similar solution. All that's added is an object that connects to HA's event loop and adds a scheduled callback to be called that propagates to all listeners. This way there's only one call to the API and all components, weather and sensors, just get notified via the `_update_callback` method which just asks HA to update the entity's state. I hope that makes sense to you.

**Comment by tathamoddie** [comment]
To test this out, I swapped my HACS component from https://github.com/bremor/bureau_of_meteorology to https://github.com/evilmarty/bureau_of_meteorology. Removing the primary repo, adding @evilmarty's as a custom repo, installing that, then restarting HA even preserved the config cleanly.

It appears to now be updating the weather entities on a reliable 10 min cycle. ✔

My config: 2x weather entities, 0x sensors.

**Comment by tathamoddie** [comment]
> Is this something that is normally done for cloud poll integrations? Is it a workaround for some weirdness that I’ve programmed in? I will spend some more time digesting what you’ve done before releasing as a beta.

Entities have a `should_poll` property on them. By default, it returns `true`, and Home Assistant takes charge of regularly nudging each entity to update.

Doco: https://developers.home-assistant.io/docs/core/entity/#polling

I _think_ this works for sensors, but the weather entity is maybe a bit different, hence this bug.

The change that @evilmarty has proposed causes the `bureau_of_meteorology` component to take ownership of the updates itself. That's driven by [the new code in `__init__.py`](https://github.com/bremor/bureau_of_meteorology/pull/53/files#diff-0b02aa1c8908f653779594663dc04d3f61aa7b23205b78bc8078d2859ab6baacR37-R46). It also adds the `should_poll` property to sensors so that they can now return `False` instead, thus telling Home Assistant "hey, we've got this ourselves".

That new code in `__init__.py` creates a single central coordinator for the updates, so that all of the weather and sensor entities update at the same time.

If this wasn't done, then each entity would drive their own polling, and that could happen at different times from each other, which might cause results to look a bit surprising. (e.g. The weather entity might say one number while a sensor still shows different/older data for a few minutes.)

**Comment by evilmarty** [comment]
That's a great analysis and explanation @tathamoddie.

**Comment by bremor** [comment]
Thanks for the great explanation, I have merged and will release as a beta.

**Pull request merged**
